# Mirror the eng/common folder to all subscribed language repos.
#
# For more information on this file, please see:
# doc/common/common_engsys.md
parameters:
- name: DirectoryToSync
  type: string
  default: eng/common
- name: Repos
  type: object
  default:
    - azure-sdk-for-go

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - eng/common

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tool-repo-sync.yml
  parameters:
    DirectoryToSync: ${{ parameters.DirectoryToSync }}
    Repos: ${{ parameters.Repos }}
